# ========================================
# Eureka Server - Docker Compose
# ========================================
services:
  eureka-server-1:
    image: jun-bank/eureka-server:latest
    container_name: eureka-server-1
    hostname: eureka-server-1
    env_file:
      - ./.env
    environment:
      - SERVER_PORT=8761
      - EUREKA_INSTANCE_HOSTNAME=eureka-server-1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server-2:8762/eureka/
    ports:
      - "8761:8761"
    networks:
      - jun-bank-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  eureka-server-2:
    image: jun-bank/eureka-server:latest
    container_name: eureka-server-2
    hostname: eureka-server-2
    env_file:
      - ./.env
    environment:
      - SERVER_PORT=8762
      - EUREKA_INSTANCE_HOSTNAME=eureka-server-2
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server-1:8761/eureka/
    ports:
      - "8762:8762"
    networks:
      - jun-bank-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8762/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

networks:
  jun-bank-network:
    external: true