services:
  eureka-server-1:
    image: ghcr.io/jun-bank/eureka-server:latest
    container_name: eureka-server-1
    hostname: eureka-server-1
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
      EUREKA_INSTANCE_HOSTNAME: eureka-server-1
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - jun-bank-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  eureka-server-2:
    image: ghcr.io/jun-bank/eureka-server:latest
    container_name: eureka-server-2
    hostname: eureka-server-2
    ports:
      - "8762:8762"
    environment:
      SERVER_PORT: 8762
      EUREKA_INSTANCE_HOSTNAME: eureka-server-2
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - jun-bank-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8762/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  jun-bank-network:
    name: jun-bank-network
    driver: bridge