# ========================================
# Account Service - Docker Compose
# ========================================
services:
  account-service:
    image: jun-bank/account-service:latest
    container_name: account-service
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    networks:
      - jun-bank-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  jun-bank-network:
    external: true