# ========================================
# User Service - Docker Compose
# ========================================
services:
  user-service:
    image: jun-bank/user-service:latest
    container_name: user-service
    env_file:
      - ./.env
    ports:
      - "8087:8087"
    networks:
      - jun-bank-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8087/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  jun-bank-network:
    external: true