# ========================================
# Transaction Service - Docker Compose
# ========================================
services:
  transaction-service:
    image: jun-bank/transaction-service:latest
    container_name: transaction-service
    env_file:
      - ./.env
    ports:
      - "8082:8082"
    networks:
      - jun-bank-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  jun-bank-network:
    external: true