services:
  gateway-server-1:
    image: ghcr.io/jun-bank/gateway-server:latest
    container_name: gateway-server-1
    hostname: gateway-server-1
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      EUREKA_INSTANCE_HOSTNAME: gateway-server-1
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - jun-bank-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway-server-2:
    image: ghcr.io/jun-bank/gateway-server:latest
    container_name: gateway-server-2
    hostname: gateway-server-2
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      EUREKA_INSTANCE_HOSTNAME: gateway-server-2
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - jun-bank-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  jun-bank-network:
    name: jun-bank-network
    driver: bridge